/** Tokens from DESIGN.md / Stitch export */
export const colors = {
  surface: "#fbf9f8",
  surfaceDim: "#dbdad9",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f5f3f3",
  surfaceContainer: "#efeded",
  surfaceContainerHigh: "#e9e8e7",
  surfaceVariant: "#e4e2e2",
  onSurface: "#1b1c1c",
  onSurfaceVariant: "#5e3f3b",
  outline: "#936e69",
  outlineVariant: "#e9bcb6",
  primary: "#b5000b",
  primaryContainer: "#e30613",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#fff5f3",
  surfaceTint: "#c0000c",
  secondary: "#5f5e5e",
  error: "#ba1a1a",
  confirmGreen: "#2E7D32",
  confirmGreenDark: "#1b5e20",
  inverseSurface: "#303031",
  black: "#1A1A1A",
} as const;
